name: vision_field_calc
description: Motor local e determinístico de cálculos técnicos Vision Field Calc.
publish_to: none
version: 0.3.0+3

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  crypto: ^3.0.6
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
    - family: NotoSansMath
      fonts:
        - asset: assets/fonts/NotoSansMath-Regular.ttf
